version: '3.9'

x-shared-logs: &shared-logs
  logging:
    driver: "json-file"
    options:
      max-size: "20k"

services:
  apt-mirror:
    network_mode: host
    build:
      context: ./apt-mirror
    #environment:
    #  http_proxy: http://proxy.example.com:8080
    #  https_proxy: http://proxy.example.com:8080
    volumes:
      - ./apt-mirror.list:/etc/apt/mirror.list
      - ./apt-mirror_data:/var/spool/apt-mirror
    <<: *shared-logs

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./apt-mirror_data:/var/spool/apt-mirror
    <<: *shared-logs
